/*
 * This source file was generated by the Gradle 'init' task
 */
package dsa;
import dsa.ExcelReader;

public class App {
    public static void main(String[] args) {
        String filePath = "C:\\Users\\Teoh Wei Hong\\Documents\\Programming\\Own study\\DSA\\DSA\\app\\src\\main\\java\\dsa\\airplane_cargo.xlsx";
        ExcelReader.ReadFromExcel(filePath);
    }
}
